### ISSUE TITLE
Negative Total Funds on Shoonya

### ISSUE THREAD

**Issue by narenkram** [narenkram/steadfast-app#11]
If you have just added funds today in your Shoonya broker account, it will not immediately reflect on the app until after a day.
This is an endpoint issue on Shoonya side, because they are not updating available cash margin immediately. So i have to find a way to handle this on the frontend using _payin_

**Comment by suresh-n** [comment]
@narenkram api.get_limits() can provide you payin which can be used. 

```
limit = api.get_limits()
marginused = (float((limit['marginused'])))
margin_available = round(((float((limit['cash']))) - marginused + float((limit['payin']))),2) 
```

**Comment by narenkram** [comment]
This issues has been fixed [fix negative total available fund (issues 11)](https://github.com/narenkram/steadfast-app/commit/ada092832103c1a9e756bae42dd1b3ff46d2a1ff)

**Comment by narenkram** [comment]
@suresh-n appreciate it, but I found a better way. When fundlimit.cash is zero, app now just shows the fundlimit.payin now.
