### ISSUE TITLE
Position Closes Automatically

### ISSUE THREAD

**Issue by narenkram** [narenkram/steadfast-app#12]
There is a very strange and rare issue that occurs immediately within seconds of creating a new position. This behavior is unexpected and I haven't been able to reproduce it.

**Temporary Solution:** Simply re-enter your position.

**Comment by narenkram** [comment]
Need to debug Target and Stoploss vue Watchers.

**Comment by narenkram** [comment]
issue still exists. if someone can fix this, please do. and let me know i'll merge it.

**Comment by arsantra** [comment]
This is amazing work , may I know how can I add other brokers , I want to add kotak , or guide me I could try

**Comment by narenkram** [comment]
this watch caused by individual stoploss and target watchers, that has been replaced with MTM stoploss and target. It's no longer a issue.
