### ISSUE TITLE
Mobile View Layout Issue

### ISSUE THREAD

**Issue by krishnasinghshahi** [narenkram/steadfast-app#15]
# Broken Mobile View

The mobile view for Steadfast is displaying the interface in an unorganized manner.

### Screenshot:

![image](https://github.com/user-attachments/assets/1ca99f83-3dba-44e6-99a3-aa9c6fcb9469)

**Details:**

- Running the latest version of Steadfast.
- Issue is visible in multiple browsers.

**Comment by narenkram** [comment]
It's not broken, I just started adding responsive design. It's not complete yet.
