### ISSUE TITLE
Unable to select positions which are SELL type.

### ISSUE THREAD

**Issue by narenkram** [narenkram/steadfast-app#16]

**Comment by krishnasinghshahi** [comment]
@narenkram Apologies for the wrong input in the above comment. I didn't notice that I had entered an extra '='. I didn't mean that netqty is a string

**Comment by narenkram** [comment]
Resolved https://github.com/narenkram/steadfast-app/commit/de7c0110e53682fa1c6584b8001a46ef88719d34
